"""empty message

Revision ID: 14df02675149
Revises: f1a1c3ce91db
Create Date: 2018-07-10 23:50:01.136184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14df02675149'
down_revision = 'f1a1c3ce91db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('total_monthly_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=32), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('fund_tree_name', sa.String(length=128), nullable=True),
    sa.Column('concat_all', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_total_monthly_mapping_account_code'), 'total_monthly_mapping', ['account_code'], unique=False)
    op.create_index(op.f('ix_total_monthly_mapping_concat_all'), 'total_monthly_mapping', ['concat_all'], unique=False)
    op.create_index(op.f('ix_total_monthly_mapping_effective_date'), 'total_monthly_mapping', ['effective_date'], unique=False)
    op.create_index(op.f('ix_total_monthly_mapping_fund_tree_name'), 'total_monthly_mapping', ['fund_tree_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_total_monthly_mapping_fund_tree_name'), table_name='total_monthly_mapping')
    op.drop_index(op.f('ix_total_monthly_mapping_effective_date'), table_name='total_monthly_mapping')
    op.drop_index(op.f('ix_total_monthly_mapping_concat_all'), table_name='total_monthly_mapping')
    op.drop_index(op.f('ix_total_monthly_mapping_account_code'), table_name='total_monthly_mapping')
    op.drop_table('total_monthly_mapping')
    # ### end Alembic commands ###
