"""empty message

Revision ID: f1a1c3ce91db
Revises: f7bb6afdac9a
Create Date: 2018-07-05 23:24:57.975407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a1c3ce91db'
down_revision = 'f7bb6afdac9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpa_total_monthly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=64), nullable=True),
    sa.Column('account_name_long', sa.String(length=64), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('performance_scheme_code', sa.Integer(), nullable=True),
    sa.Column('asset_class', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=64), nullable=True),
    sa.Column('security_name', sa.String(length=64), nullable=True),
    sa.Column('security_name_long', sa.String(length=64), nullable=True),
    sa.Column('sec_ssc_id', sa.String(length=64), nullable=True),
    sa.Column('emv', sa.Float(), nullable=True),
    sa.Column('bmv', sa.Float(), nullable=True),
    sa.Column('abal', sa.Float(), nullable=True),
    sa.Column('abal_zero', sa.Float(), nullable=True),
    sa.Column('abal_mid', sa.Float(), nullable=True),
    sa.Column('abal_full', sa.Float(), nullable=True),
    sa.Column('base_flows', sa.Float(), nullable=True),
    sa.Column('value_add', sa.Float(), nullable=True),
    sa.Column('gain_loss', sa.Float(), nullable=True),
    sa.Column('inc', sa.Float(), nullable=True),
    sa.Column('inflws', sa.Float(), nullable=True),
    sa.Column('otflw_val', sa.Float(), nullable=True),
    sa.Column('net_csh_flw', sa.Float(), nullable=True),
    sa.Column('ror', sa.Float(), nullable=True),
    sa.Column('rates_rule', sa.Integer(), nullable=True),
    sa.Column('mgr_fees', sa.Float(), nullable=True),
    sa.Column('oth_fees', sa.Float(), nullable=True),
    sa.Column('index_code', sa.String(length=64), nullable=True),
    sa.Column('index_ror', sa.Float(), nullable=True),
    sa.Column('index_short_name', sa.String(length=128), nullable=True),
    sa.Column('account_type', sa.String(length=64), nullable=True),
    sa.Column('daily_flag', sa.String(length=64), nullable=True),
    sa.Column('as_of_tms', sa.DateTime(), nullable=True),
    sa.Column('as_at_tms', sa.Integer(), nullable=True),
    sa.Column('p_c_flag', sa.String(length=4), nullable=True),
    sa.Column('country_date', sa.DateTime(), nullable=True),
    sa.Column('day_type', sa.Integer(), nullable=True),
    sa.Column('monthend', sa.Integer(), nullable=True),
    sa.Column('last_business_date', sa.DateTime(), nullable=True),
    sa.Column('next_business_date', sa.DateTime(), nullable=True),
    sa.Column('last_month_end_date', sa.DateTime(), nullable=True),
    sa.Column('next_month_end_date', sa.DateTime(), nullable=True),
    sa.Column('bda_as_at_tms', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpa_total_monthly_account_code'), 'gpa_total_monthly', ['account_code'], unique=False)
    op.create_index(op.f('ix_gpa_total_monthly_account_name_long'), 'gpa_total_monthly', ['account_name_long'], unique=False)
    op.create_index(op.f('ix_gpa_total_monthly_account_type'), 'gpa_total_monthly', ['account_type'], unique=False)
    op.create_index(op.f('ix_gpa_total_monthly_daily_flag'), 'gpa_total_monthly', ['daily_flag'], unique=False)
    op.create_index(op.f('ix_gpa_total_monthly_effective_date'), 'gpa_total_monthly', ['effective_date'], unique=False)
    op.create_index(op.f('ix_gpa_total_monthly_index_code'), 'gpa_total_monthly', ['index_code'], unique=False)
    op.create_index(op.f('ix_gpa_total_monthly_p_c_flag'), 'gpa_total_monthly', ['p_c_flag'], unique=False)
    op.create_index(op.f('ix_gpa_total_monthly_rates_rule'), 'gpa_total_monthly', ['rates_rule'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gpa_total_monthly_rates_rule'), table_name='gpa_total_monthly')
    op.drop_index(op.f('ix_gpa_total_monthly_p_c_flag'), table_name='gpa_total_monthly')
    op.drop_index(op.f('ix_gpa_total_monthly_index_code'), table_name='gpa_total_monthly')
    op.drop_index(op.f('ix_gpa_total_monthly_effective_date'), table_name='gpa_total_monthly')
    op.drop_index(op.f('ix_gpa_total_monthly_daily_flag'), table_name='gpa_total_monthly')
    op.drop_index(op.f('ix_gpa_total_monthly_account_type'), table_name='gpa_total_monthly')
    op.drop_index(op.f('ix_gpa_total_monthly_account_name_long'), table_name='gpa_total_monthly')
    op.drop_index(op.f('ix_gpa_total_monthly_account_code'), table_name='gpa_total_monthly')
    op.drop_table('gpa_total_monthly')
    # ### end Alembic commands ###
